document.write( 
  "<a  name='contact'></a> ",
   " <div class='bannertop'> ",
"        <div class='container'> ",
 "           <div class='row'> ",
"                <div class='col-lg-6'> ",
"                </div> ",
 "               <div class='col-lg-6'> ",
  "                  <ul class='list-inline banner-social-buttons'> ",
   "                     <li> ",
    "                        <a href='#' class='btn btn-default btn-lg'><i class='fa fa-twitter fa-fw'></i> <span class='network-name'>Twitter</span></a> ",
     "                   </li> ",
      "                  <li> ",
       "                     <a href='#' class='btn btn-default btn-lg'><i class='fa fa-github fa-fw'></i> <span class='network-name'>Github</span></a> ",
        "                </li> ",
         "               <li> ",
          "                  <a href='#' class='btn btn-default btn-lg'><i class='fa fa-linkedin fa-fw'></i> <span class='network-name'>Linkedin</span></a> ",
           "             </li> ",
 "                   </ul> ",
  "              </div> ",
   "         </div> ",
"        </div> ",
 "       <!-- /.container --> ",
  "   </div> ");

// image for banner is in landing-page.css under the bannertop class.