document.write( 
    "<!-- Navigation --> ",
    "<nav class='navbar navbar-default navbar-fixed-top topnav' role='navigation'> ",
        "<div class='container topnav'> ",
         "   <!-- Brand and toggle get grouped for better mobile display --> ",
          "  <div class='navbar-header'> ",
           "     <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1'> ",
            "        <span class='sr-only'>Toggle navigation</span> ",
             "       <span class='icon-bar'></span> ",
              "      <span class='icon-bar'></span> ",
               "     <span class='icon-bar'></span> ",
               " </button> ",
               " <a class='navbar-brand topnav' href='../index.html'>BSYS CONCORDIA</a> ",
            "</div> ",
            "<!-- Collect the nav links, forms, and other content for toggling --> ",
            "<div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'> ",
            "    <ul class='nav navbar-nav navbar-right'> ",                    
                            "  <li><a href='aboutus.html'>About us</a></li> ",
                      " </li> ",        
          "      <li> ",
               "         <a href='events.html'>Events</a> ",
                "    </li> ",
                 "   <li> ",
                  "      <a href='getInvolved.html'>Get Involved</a> ",
           "         </li> ",
            "        <li> ",
             "           <a href='under_construction.html'>Projects</a> ",
              "      </li> ",
               "     <li> ",
                "        <a href='contactus.html'>Contact Us</a> ",
                "   </li> ",
                 "     <li> ",
                "        <a href='under_construction.html'>FAQ</a> ",
                "   </li> ",
             "     </ul> ",
           " </div> ",
           " <!-- /.navbar-collapse --> ",
       " </div> ",
       " </nav>");