document.write( 
    "<!-- Navigation --> ",
    "<nav class='navbar navbar-default navbar-fixed-top topnav' role='navigation'> ",
        "<div class='container topnav'> ",
         "   <!-- Brand and toggle get grouped for better mobile display --> ",
          "  <div class='navbar-header'> ",
           "     <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1'> ",
            "        <span class='sr-only'>Toggle navigation</span> ",
             "       <span class='icon-bar'></span> ",
              "      <span class='icon-bar'></span> ",
               "     <span class='icon-bar'></span> ",
               " </button> ",
               " <a class='navbar-brand topnav' href='../index.html'>BSYS CONCORDIA</a> ",
            "</div> ",
            "<!-- Collect the nav links, forms, and other content for toggling --> ",
            "<div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'> ",
            "    <ul class='nav navbar-nav navbar-right'> ",
                    
             "        <li class='dropdown'> ",
             "           <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>About Us<span class='caret'></span></a> ",
              "          <ul class='dropdown-menu'> ",
               "             <li><a href='./index.html'>BSYS at Concordia</a></li> ",
                "            <li><a href='./pages/whoami.html'>Team Members</a></li> ",
                 "       </ul> ",
             "       </li> ",        
          "      <li> ",
               "         <a href='./pages/events.html'>Events</a> ",
                "    </li> ",
                 "   <li> ",
                  "      <a href='./pages/under_construction.html'>Get Involved</a> ",
           "         </li> ",
            "        <li> ",
             "           <a href='./pages/under_construction.html'>Projects</a> ",
              "      </li> ",
               "     <li> ",
                "        <a href='./pages/under_construction.html'>Contact Us</a> ",
                 "   </li> ",
                "    <li> ",
                 "       <a href='./pages/under_construction.html'>FAQ</a> ",
                  "  </li> ",
           "     </ul> ",
           " </div> ",
           " <!-- /.navbar-collapse --> ",
       " </div> ",
       " </nav>");